services :
  nginx :
    build       : nginx
    ports       : 
      - "443:443"
    depends_on :
      - wordpress
    volumes     :
      - wordpress_files:/var/www/html
  mariadb :
    build       : mariadb
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: db1
      MYSQL_USER: user1
      MYSQL_PASSWORD: user123
    # ports       : 
    #   - "3306:3306"
    volumes     :
      - wordpress_db:/var/lib/mysql
    
  wordpress     :
    build       : wordpress
    environment:
      DB_NAME: db1
      DB_USER: user1
      DB_PASSWORD: user123
      DB_HOST: mariadb
    depends_on :
      - mariadb
    volumes     :
      - wordpress_files:/var/www/html
volumes :
  wordpress_db :
  wordpress_files :
     
